Repository AY2122S1-CS2103T-W10-3/tp, pull requests merged in 2021-11, with the labels that each got.

#172 Fix PED issues for UG
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/skill/Framework.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: documentation, severity.Low

#182 PED Filter bugs resolved
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
Labels: documentation, type.Bug, priority.Medium, severity.Medium, type.testing, type.FeatureFlaw, type.DocumentationBug

#187 Update UserGuide.md to fix conflicts in earlier PR
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AppendCommand.java
  src/main/java/seedu/address/logic/commands/RemoveCommand.java
Labels: documentation

#188 DG changes and PPP Update
  docs/DeveloperGuide.md
  docs/images/FilterCommandSequenceDiagram.png
  docs/team/shivlock221b.md
Labels: documentation, priority.High, type.DocumentationBug

#189 Update sample data for new user
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: severity.Low

#192 Update DeveloperGuide.md for v1.4
  docs/DeveloperGuide.md
  docs/diagrams/AppendActivityDiagram.puml
  docs/diagrams/AppendSequenceDiagram.puml
  docs/diagrams/AppendSequenceDiagram2.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AppendActivityDiagram.png
  docs/images/AppendSequenceDiagram.png
  docs/images/AppendSequenceDiagram2.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#194 Update and reformat DG
  docs/DeveloperGuide.md
Labels: documentation

#199 Update UG and DG with diagrams
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/AddCommand.png
  docs/images/AppendCommand.png
  docs/images/DeleteCommand1.png
  docs/images/DeleteCommand2.png
  docs/images/EditCommand.png
  docs/images/Help.png
  docs/images/RemoveCommand.png
  docs/images/Ui.png
Labels: documentation

#200 Update PPP in timothywong.md
  docs/team/timothywong.md
Labels: documentation

#202 Format documentation for UG and DG with minor changes
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Help.png
  docs/images/SortCommand.png
  docs/images/Ui.png
  docs/index.md
Labels: documentation
